apiVersion: v1
kind: Service
metadata:
  name: commande-service
spec:
  selector:
    app: commande-app   
  ports:
    - protocol: TCP
      port: 8001       
      targetPort: 8001
  type: LoadBalancer
  
  